visual-tests:
  description: To ensure code quality, runs visual tests for a javascript React application using Chromatic
  runs-on: ubuntu-latest
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup pnpm
      uses: pnpm/action-setup@v4

    - uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc
        cache: "pnpm"

    - name: Install dependencies
      run: make install

    - uses: chromaui/action@v13
      with:
        projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
        exitZeroOnChanges: false # Fail workflow if changes are found
