name: Visual Tests
description: To ensure code quality, runs visual tests for a javascript React application using Chromatic

inputs:
  CHROMATIC_PROJECT_TOKEN:
    description: Chromatic project token
    required: true
  AWS_ACCOUNT_ID:
    description: AWS Account ID hosting CodeArtifact
    required: true
  AWS_REGION:
    description: AWS region hosting CodeArtifact
    required: true
  AWS_ROLE_TO_ASSUME:
    description: AWS role to assume for CodeArtifact repository access
    required: true
  AWS_CODE_ARTIFACT_DOMAIN:
    description: AWS CodeArtifact domain
    required: true
  AWS_CODE_ARTIFACT_REPOSITORY:
    description: AWS CodeArtifact repository
    required: true
  REGISTRY_NAMESPACE:
    description: Namespace to use for registry authentication.
    required: true


runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        # 👇 Tells the checkout which commit hash to reference
        # Mentioned in the docs here:
        # https://www.chromatic.com/docs/github-actions/#recommended-configuration-for-build-events
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Setup pnpm
      uses: pnpm/action-setup@v4

    - uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc
        cache: "pnpm"

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ inputs.AWS_REGION }}
        role-to-assume: ${{ inputs.AWS_ROLE_TO_ASSUME }}

    - name: Install Dependencies
      env:
          AWS_CODE_ARTIFACT_DOMAIN: ${{ inputs.AWS_CODE_ARTIFACT_DOMAIN }}
          AWS_ACCOUNT_ID: ${{ inputs.AWS_ACCOUNT_ID }}
          AWS_CODE_ARTIFACT_REPOSITORY: ${{ inputs.AWS_CODE_ARTIFACT_REPOSITORY }}
          REGISTRY_NAMESPACE: ${{ inputs.REGISTRY_NAMESPACE }}
      run: make install
      shell: bash

    # Run storybook doctor
    - name: Run Storybook Doctor for Web
      run: pnpm doctor:storybook:web
      shell: bash

    - name: Run Storybook Doctor for Native
      run: pnpm doctor:storybook:native
      shell: bash

    # Chromatic runs build-storybook for the web, but we need to check the native storybook ourselves
    - name: Build iOS Storybook
      run: pnpm build-storybook:ios
      shell: bash

    - name: Run Chromatic
      uses: chromaui/action@v18
      with:
        projectToken: ${{ inputs.CHROMATIC_PROJECT_TOKEN }}
        # This action is just responsible for kicking off the tests
        # Chromatic will then trigger the UI Tests action which is responsible for
        # either pass or fail based on a Chromatic review
        exitZeroOnChanges: true
        # This strategy is explained here: https://www.chromatic.com/docs/github-actions/#github-squashrebase-merge-and-the-main-branch
        # If you’re using this functionality but notice the incoming changes were not accepted
        # as baselines in Chromatic, then you’ll need to adjust the workflow to include a new
        # step with the autoAcceptChanges option.
        # If we run this on main, we want to auto accept changes, assuming this already ran on
        # the incoming PR
        autoAcceptChanges: "main"
      env:
          CHROMATIC_BRANCH: ${{ github.event.pull_request.head.ref || github.ref_name }}
          CHROMATIC_SHA: ${{ github.event.pull_request.head.sha || github.ref }}
          CHROMATIC_SLUG: ${{ github.repository }}
