description: To ensure code quality, runs visual tests for a javascript React application using Chromatic

inputs:
  projectToken:
    description: Chromatic project token
    required: true

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup pnpm
      uses: pnpm/action-setup@v4

    - uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc
        cache: "pnpm"

    - name: Install dependencies
      run: make install
      shell: bash

    - uses: chromaui/action@v13
      with:
        projectToken: ${{ inputs.projectToken }}
        # This action is just responsible for kicking off the tests
        # Chromatic will then trigger the UI Tests action which is responsible for
        # either pass or fail based on a Chromatic review
        exitZeroOnChanges: true
