description: To ensure code quality, runs lint, test, and build steps for a javascript repository managed with pnpm.
runs:
  using: composite
  steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Environment
        run: make setup-env
        shell: bash

      # without an explicit version, will grab the packageManager version from the package.json
      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'pnpm'

      - name: Install Dependencies
        run: make install
        shell: bash

      - name: Lint
        run: make lint
        shell: bash

      - name: Test
        run: make test
        shell: bash

      - name: Build
        run: make build
        shell: bash
