---
commitizen:
  customize:
    bump_map:
      build: PATCH
      chore: PATCH
      docs: PATCH
      feat: MINOR
      fix: PATCH
      perf: PATCH
      refactor: PATCH
      style: PATCH
      test: PATCH
    bump_pattern: ^(feat|fix|perf|refactor|chore|style|build|docs|test)
  name: cz_customize
  tag_format: $version
  update_changelog_on_bump: true
  version: 2.1.5
  version_scheme: semver
