name: Quality Gate
description: To ensure code quality, runs lint, test, and build steps for a javascript repository managed with yarn.
runs:
  using: composite
  steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable
        shell: bash

      - name: Set Node & Yarn Versions
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: yarn

      - name: Install Dependencies
        run: yarn install
        shell: bash

      - name: Lint
        run: yarn lint
        shell: bash

      - name: Test
        run: yarn coverage
        shell: bash

      - name: Build
        run: yarn build
        shell: bash
