name: Merge Workflow

on:
  push:
    branches:
      - test

jobs:
  bump-version:
    runs-on: ubuntu-latest
    name: Bump Version & Create Changelog
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - uses: commitizen-tools/commitizen-action@0.24.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
