name: Merge Workflow

on:
  push:
    branches:
      - main

jobs:
  publish:
    permissions:
      contents: write
    uses: ./.github/workflows/publish.yml
    with:
      # required to bypass branch protection in user-owned repositories
      github-app-client-id: ${{ vars.GH_WORKFLOWS_APP_CLIENT_ID }}
    secrets:
      github-app-private-key: ${{ secrets.GH_WORKFLOWS_APP_PRIVATE_KEY }}
