name: Pull Request Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  quality-gate:
    name: Quality Gate # required: it is part of the check name (Quality Gate / Core)
    permissions:
      contents: read
    uses: ./.github/workflows/pull-request.yml
